spring:
  cloud:
    nacos:
      discovery:
        ###服务注册地址
        server-addr: 127.0.0.1:8848
  application:
    name: dandan_user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vote_center?useSSL=false&connectTimeout=3000&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password:
    driver-class-name:
server:
  port: 8080
